AWS Migration

diff --git a/.github/workflows/cdkactions_build-and-deploy.yaml b/.github/workflows/cdkactions_build-and-deploy.yaml
--- a/.github/workflows/cdkactions_build-and-deploy.yaml
+++ b/.github/workflows/cdkactions_build-and-deploy.yaml
@@ -53,17 +53,26 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Publish
-        uses: docker/build-push-action@v1
+      - uses: docker/setup-qemu-action@v1
+      - uses: docker/setup-buildx-action@v1
+      - name: Cache Docker layers
+        uses: actions/cache@v2
         with:
-          repository: pennlabs/office-hours-queue-backend
-          path: backend
-          dockerfile: backend/Dockerfile
+          path: /tmp/.buildx-cache
+          key: buildx-publish-backend
+      - uses: docker/login-action@v1
+        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Build/Publish
+        uses: docker/build-push-action@v2
+        with:
+          context: backend
+          file: backend/Dockerfile
           push: ${{ github.ref == 'refs/heads/master' }}
-          tags: latest,${{ github.sha }}
-          cache_froms: pennlabs/office-hours-queue-backend:latest
+          cache-from: type=local,src=/tmp/.buildx-cache,type=registry,ref=pennlabs/office-hours-queue-backend:latest
+          cache-to: type=local,dest=/tmp/.buildx-cache
+          tags: pennlabs/office-hours-queue-backend:latest,pennlabs/office-hours-queue-backend:${{ github.sha }}
     needs: django-check
   react-check:
     name: React Check
@@ -99,30 +108,37 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Publish
-        uses: docker/build-push-action@v1
+      - uses: docker/setup-qemu-action@v1
+      - uses: docker/setup-buildx-action@v1
+      - name: Cache Docker layers
+        uses: actions/cache@v2
         with:
-          repository: pennlabs/office-hours-queue-frontend
-          path: frontend
-          dockerfile: frontend/Dockerfile
+          path: /tmp/.buildx-cache
+          key: buildx-publish-frontend
+      - uses: docker/login-action@v1
+        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Build/Publish
+        uses: docker/build-push-action@v2
+        with:
+          context: frontend
+          file: frontend/Dockerfile
           push: ${{ github.ref == 'refs/heads/master' }}
-          tags: latest,${{ github.sha }}
-          cache_froms: pennlabs/office-hours-queue-frontend:latest
+          cache-from: type=local,src=/tmp/.buildx-cache,type=registry,ref=pennlabs/office-hours-queue-frontend:latest
+          cache-to: type=local,dest=/tmp/.buildx-cache
+          tags: pennlabs/office-hours-queue-frontend:latest,pennlabs/office-hours-queue-frontend:${{ github.sha }}
     needs: react-check
   deploy:
     runs-on: ubuntu-latest
     container:
-      image: pennlabs/helm-tools:c964e53d3e3e88d36677e84f5437da40a289c7a4
+      image: pennlabs/helm-tools:39b60af248944898fcbc58d1fe5b0f1995420aef
     if: github.ref == 'refs/heads/master'
     steps:
       - uses: actions/checkout@v2
       - name: Deploy
         run: |-
-          curl -s -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $DO_AUTH_TOKEN" "https://api.digitalocean.com/v2/kubernetes/clusters/${K8S_CLUSTER_ID}/kubeconfig" > /kubeconfig.conf
-
-          export KUBECONFIG=/kubeconfig.conf
+          aws eks --region us-east-1 update-kubeconfig --name production --role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/kubectl
 
           # get repo name (by removing owner/organization)
           RELEASE_NAME=${REPOSITORY#*/}
@@ -135,14 +151,24 @@ jobs:
           fi
 
           helm repo add pennlabs https://helm.pennlabs.org/
-
           for i in {1..10}; do
-            helm upgrade --install --atomic --set=image_tag=$IMAGE_TAG -f k8s/values.yaml --version "${DEPLOY_TAG}" $RELEASE_NAME pennlabs/icarus && exit 0
+            # This is bash soup, but it'll do.
+            # 1. Attempt to install with helm
+            # 2. If this succeeds, exit with a success status code
+            # 3. If it fails, mark the command as succeeded so that '-e' doesn't kick us out
+            # 4. Wait 10s and try again
+            helm upgrade --install --atomic --set=image_tag=$IMAGE_TAG -f k8s/values.yaml --version "${DEPLOY_TAG}" $RELEASE_NAME pennlabs/icarus && exit 0 || true
             sleep 10s
             echo "Retrying deploy for $i times"
           done
+
+          # If we get here, all helm installs failed so our command should fail
+          exit 1
         env:
           IMAGE_TAG: ${{ github.sha }}
+          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.GH_AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.GH_AWS_SECRET_ACCESS_KEY }}
           DO_AUTH_TOKEN: ${{ secrets.DO_AUTH_TOKEN }}
           K8S_CLUSTER_ID: ${{ secrets.K8S_CLUSTER_ID }}
           REPOSITORY: ${{ github.repository }}
